### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by peccu** [peccu/vite-vue3-tailwind3#1]
- [ ] add vue-router
- [ ] add eslint, prettier
- [ ] netlify deploy config
- [ ] gh pages deploy config
- [ ] …
